import type {
  Advisor,
  Degree,
  Department,
  Evaluation,
  Quota,
  School,
  SchoolCode,
  SchoolGroup,
  TraceItem,
} from './types'

// C9 顺序按联盟成立公告原序：清华、北大、复旦、上交、南大、浙大、中科大、哈工深、西安交大。
export const C9_SCHOOLS: SchoolCode[] = [
  'tsinghua',
  'pku',
  'fudan',
  'sjtu',
  'nju',
  'zju',
  'ustc',
  'hitsz',
  'xjtu',
]

export const SCHOOL_GROUPS: SchoolGroup[] = [
  { code: 'top2', label: 'Top2', schools: ['tsinghua', 'pku', 'thusz', 'pkusz'] },
  { code: 'hwu', label: '华五', schools: ['fudan', 'sjtu', 'nju', 'zju', 'ustc'] },
  { code: 'c9', label: 'C9 高校', schools: C9_SCHOOLS },
  // "高校信息" 的 chips 在运行时由 SchoolsPage 从 /schools/meta 拼出来
  // —— 只显示数据库里实际收录、且**不在 C9 联盟**里的学校（与 C9 tab
  // 互补）。schools 字段留空作占位；SchoolChips 会用动态列表替换。
  { code: 'all', label: '高校信息', schools: [] },
]

export const SCHOOLS: Partial<Record<SchoolCode, School>> = {
  tsinghua: { code: 'tsinghua', name_cn: '清华大学', short: '清华', city: '北京' },
  pku: { code: 'pku', name_cn: '北京大学', short: '北大', city: '北京' },
  fudan: { code: 'fudan', name_cn: '复旦大学', short: '复旦', city: '上海' },
  sjtu: { code: 'sjtu', name_cn: '上海交通大学', short: '上交', city: '上海' },
  nju: { code: 'nju', name_cn: '南京大学', short: '南大', city: '南京' },
  zju: { code: 'zju', name_cn: '浙江大学', short: '浙大', city: '杭州' },
  ustc: { code: 'ustc', name_cn: '中国科学技术大学', short: '中科大', city: '合肥' },
  hit: { code: 'hit', name_cn: '哈尔滨工业大学', short: '哈工大', city: '哈尔滨' },
  hitsz: { code: 'hitsz', name_cn: '哈尔滨工业大学（深圳）', short: '哈工深', city: '深圳' },
  pkusz: { code: 'pkusz', name_cn: '北京大学深圳研究生院', short: '北大深圳', city: '深圳' },
  thusz: { code: 'thusz', name_cn: '清华大学深圳国际研究生院', short: '清华深圳', city: '深圳' },
  xjtu: { code: 'xjtu', name_cn: '西安交通大学', short: '西交', city: '西安' },
}

const S = (code: SchoolCode) => ({ code, name_cn: SCHOOLS[code]?.name_cn ?? code })
const D = (code: string, name: string): Department => ({ code, name_cn: name })
const Q = (
  year: number | null,
  degree: Degree | null,
  count: number | null,
  conf: number | null,
  raw: string,
  src: string,
): Quota => ({ year, degree, count, confidence: conf, raw_text: raw, source_url: src })
const E = (src: string, url: string, content: string, posted: string | null): Evaluation => ({
  source: src,
  source_url: url,
  content,
  posted_at: posted,
})
const T = (kind: TraceItem['kind'], label: string, detail: string): TraceItem => ({
  kind,
  label,
  detail,
})

export const ADVISORS: Advisor[] = [
  /* ============ 清华大学 ============ */
  {
    id: 101,
    school: S('tsinghua'),
    departments: [D('cs', '计算机科学与技术系'), D('iiis', '交叉信息研究院')],
    name_cn: '姚明轩',
    title: '助理教授',
    homepage: 'https://www.cs.tsinghua.edu.cn/info/1116/3812.htm',
    source_url: 'https://www.cs.tsinghua.edu.cn/info/1116/3812.htm',
    email: 'yaomx@tsinghua.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text:
      '清华大学交叉信息院助理教授,2023 年从 MIT EECS 毕业。研究方向为大语言模型推理、可解释性与对齐。',
    research_interests: ['LLM 推理', '可解释性', 'AI 对齐', '机器学习理论'],
    is_recruiting: true,
    recruiting_confidence: 0.85,
    reputation_tag: 'positive',
    enriched_summary:
      '姚老师 2026 年招收 PhD 2 名 + 硕士 1 名,方向集中在 LLM 推理与可解释性。学生反馈:idea sharing 频繁、论文产出稳定(组里近两年 NeurIPS/ICML 共 6 篇)、不打卡、海外合作机会多。建议有数学/理论基础的同学优先考虑。',
    last_enriched_at: '2026-05-18T10:24:00Z',
    quotas: [
      Q(
        2026,
        'PhD',
        2,
        0.9,
        '官网招生计划页明确"2026 年招收博士生 2 名"',
        'https://iiis.tsinghua.edu.cn/yao-recruit',
      ),
      Q(
        2026,
        'MS',
        1,
        0.8,
        '硕士导师名单中列入,招收 1 名学硕',
        'https://www.cs.tsinghua.edu.cn/zsxx.htm',
      ),
      Q(
        2026,
        'Postdoc',
        null,
        0.5,
        '组会页提到"长期招收博后,coding ability strong preferred"',
        'https://iiis.tsinghua.edu.cn/yao-recruit',
      ),
    ],
    evaluations: [
      E(
        'zhihu.com',
        'https://zhihu.com/q/12345',
        '组里 vibe 很好,Yao 老师每周一对一,push 强度适中。组里有 MIT/CMU 访学渠道。',
        '2026-03-12',
      ),
      E(
        'csrankings.org',
        'https://csrankings.org/yaomx',
        'h-index 18, 近 5 年发表 ICML/NeurIPS/ICLR 27 篇。',
        '2026-01-08',
      ),
    ],
    trace: [
      T('search', '搜索', '"姚明轩 清华 招生 2026" → 12 results'),
      T('read', '阅读', 'iiis.tsinghua.edu.cn/yao-recruit → 2400 chars'),
      T('search', '搜索', '"yao mx zhihu 评价" → 8 results'),
      T('read', '阅读', 'zhihu.com/q/12345 → 1800 chars'),
      T('final', '提交评价', '招生·positive·conf=0.85'),
    ],
  },
  {
    id: 102,
    school: S('tsinghua'),
    departments: [D('cs', '计算机科学与技术系')],
    name_cn: '李振华',
    title: '教授',
    homepage: 'https://www.cs.tsinghua.edu.cn/info/1116/2841.htm',
    source_url: 'https://www.cs.tsinghua.edu.cn/info/1116/2841.htm',
    email: 'lizhenhua@mail.tsinghua.edu.cn',
    email_obfuscated: false,
    phone: '010-62795826',
    photo_url: null,
    bio_text: null,
    research_interests: ['网络与系统', '边缘计算', '移动计算'],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: 'neutral',
    enriched_summary:
      '组里以系统方向为主,SIGCOMM/MobiCom 产出稳定。学生评价中性偏正面:工作节奏 9-9-5,产出导向,论文 push 较强。2026 年招生未明确表态,建议先邮件咨询。',
    last_enriched_at: '2026-05-10T03:40:00Z',
    quotas: [],
    evaluations: [
      E(
        'yanjubian.com',
        'https://yanjubian.com/t/topic/1102',
        '组里偏工程,会有大厂合作项目,毕业去向以 BAT 系统部门为主。',
        '2025-12-04',
      ),
    ],
    trace: [
      T('search', '搜索', '"李振华 清华 计算机 招生" → 6 results'),
      T('read', '阅读', 'cs.tsinghua.edu.cn/info/1116/2841 → 1200 chars'),
      T('final', '提交评价', '招生未明·neutral·conf=null'),
    ],
  },
  {
    id: 103,
    school: S('tsinghua'),
    departments: [D('air', '智能产业研究院 AIR')],
    name_cn: '陈墨',
    title: '副教授',
    homepage: 'https://air.tsinghua.edu.cn/info/1009/1218.htm',
    source_url: 'https://air.tsinghua.edu.cn/info/1009/1218.htm',
    email: 'chenmo@air.tsinghua.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['自动驾驶', '具身智能'],
    is_recruiting: true,
    recruiting_confidence: 0.7,
    reputation_tag: 'unknown',
    enriched_summary: null,
    last_enriched_at: '2026-04-22T08:10:00Z',
    quotas: [
      Q(
        2026,
        'PhD',
        null,
        0.7,
        '组会页提及"2026 招博",未给具体名额',
        'https://air.tsinghua.edu.cn/chen-recruit',
      ),
    ],
    evaluations: [],
    trace: [
      T('search', '搜索', '"陈墨 AIR 清华 招生" → 4 results'),
      T('read', '阅读', 'air.tsinghua.edu.cn/info/1009/1218 → 800 chars'),
      T('final', '提交评价', '招生·unknown·conf=0.7'),
    ],
  },
  {
    id: 104,
    school: S('tsinghua'),
    departments: [D('iiis', '交叉信息研究院')],
    name_cn: '徐沛然',
    title: '助理教授',
    homepage: 'https://iiis.tsinghua.edu.cn/xupr',
    source_url: 'https://iiis.tsinghua.edu.cn/xupr',
    email: 'xupr@tsinghua.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: '研究方向:博弈论、经济学与计算的交叉。',
    research_interests: ['博弈论', '机制设计', '算法经济学'],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: null,
    enriched_summary: null,
    last_enriched_at: null,
    quotas: [],
    evaluations: [],
    trace: [],
  },
  {
    id: 105,
    school: S('tsinghua'),
    departments: [D('cs', '计算机科学与技术系'), D('thuai', '人工智能研究院')],
    name_cn: '王思颖',
    title: '副教授',
    homepage: 'https://www.cs.tsinghua.edu.cn/info/1116/3501.htm',
    source_url: 'https://www.cs.tsinghua.edu.cn/info/1116/3501.htm',
    email: 'wangsy@tsinghua.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: 'IEEE Fellow,主要研究方向为计算机视觉与多模态学习。',
    research_interests: ['计算机视觉', '多模态学习', 'Diffusion Models', '生成模型'],
    is_recruiting: true,
    recruiting_confidence: 0.95,
    reputation_tag: 'positive',
    enriched_summary:
      '王老师组 2026 年招收博士 3 名 + 硕士 2 名,方向以多模态生成为主。组里近两年 CVPR/ICCV 顶会接收 14 篇。学生评价:导师亲和、组氛围 collaborative、有海外合作机会、奖学金充足(月补 6k+)。强烈推荐。',
    last_enriched_at: '2026-05-19T11:00:00Z',
    quotas: [
      Q(
        2026,
        'PhD',
        3,
        0.95,
        '官网招生页明确"2026 招博士 3 名"',
        'https://www.cs.tsinghua.edu.cn/wang-recruit',
      ),
      Q(2026, 'MS', 2, 0.9, '硕士名单中招收 2 名', 'https://www.cs.tsinghua.edu.cn/zsxx.htm'),
    ],
    evaluations: [
      E(
        'zhihu.com',
        'https://zhihu.com/q/53421',
        '王老师是少有的真把学生当人看的老板,组里 work-life balance 不错。',
        '2026-04-01',
      ),
      E(
        'daoshipingjia.net',
        'https://daoshipingjia.net/teacher/22011',
        '综合 4.8/5。指导能力、组氛围、毕业前景均高分。',
        '2026-02-15',
      ),
    ],
    trace: [
      T('search', '搜索', '"王思颖 清华 招生" → 18 results'),
      T('read', '阅读', '3 sources'),
      T('final', '提交评价', '招生·positive·conf=0.95'),
    ],
  },
  {
    id: 106,
    school: S('tsinghua'),
    departments: [D('cs', '计算机科学与技术系')],
    name_cn: '钟海涛',
    title: '教授',
    homepage: 'https://www.cs.tsinghua.edu.cn/info/1116/2003.htm',
    source_url: 'https://www.cs.tsinghua.edu.cn/info/1116/2003.htm',
    email: 'htzhong@tsinghua.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['数据库系统', '分布式系统'],
    is_recruiting: false,
    recruiting_confidence: 0.85,
    reputation_tag: 'neutral',
    enriched_summary: '钟老师 2026 年明确不招博士(已满员),硕士名额已锁定推免生。可考虑明年再联系。',
    last_enriched_at: '2026-04-30T05:00:00Z',
    quotas: [
      Q(
        2026,
        'PhD',
        0,
        0.9,
        '官网招生页:"2026 年不招收新博士生"',
        'https://www.cs.tsinghua.edu.cn/zhong-recruit',
      ),
    ],
    evaluations: [],
    trace: [
      T('search', '搜索', '"钟海涛 清华 2026 招生" → 5 results'),
      T('final', '提交评价', '不招·neutral·conf=0.85'),
    ],
  },

  /* ============ 北京大学 ============ */
  {
    id: 201,
    school: S('pku'),
    departments: [D('eecs', '计算机学院')],
    name_cn: '易江芳',
    title: '副教授',
    homepage: 'https://cs.pku.edu.cn/info/1085/1724.htm',
    source_url: 'https://cs.pku.edu.cn/info/1085/1724.htm',
    email: 'yijiangfang@mprc.pku.edu.cn',
    email_obfuscated: false,
    phone: '86-10-62765828-832',
    photo_url: null,
    bio_text:
      '易江芳,北京大学信息科学技术学院计算机系副教授,长期从事微处理器体系结构设计和性能优化科研及教学工作。',
    research_interests: ['计算机体系结构', '微处理器'],
    is_recruiting: true,
    recruiting_confidence: 0.8,
    reputation_tag: 'negative',
    enriched_summary:
      '易江芳(北大计算机学院,系统结构研究所)2026 年可招收硕士(列入硕士导师名单),但未列入博士导师名单。学生评价负面:学术指导有限、科研经费不充裕、管理严格(钉钉打卡考勤、长时间坐班)、不允许实习、补助偏低、沟通风格不佳。建议谨慎选择,尤其不适合期望高学术产出、自由科研环境或需要实习经历的学生。',
    last_enriched_at: '2026-05-20T08:24:00Z',
    quotas: [
      Q(
        2026,
        'MS',
        null,
        0.9,
        '在硕士指导教师名单中(系统结构方向)',
        'https://cs.pku.edu.cn/zsxx/yjszs/dsxx.htm',
      ),
      Q(
        2026,
        'PhD',
        null,
        0.9,
        '未列入博士指导教师名单',
        'https://cs.pku.edu.cn/zsxx/yjszs/dsxx.htm',
      ),
    ],
    evaluations: [
      E(
        'yanjubian.com',
        'https://yanjubian.com/t/topic/7943',
        '学生反馈整理:多条评价指出导师个人及指导学生发表的论文数量不多,学术指导支持有限;科研经费不太充裕;管理严格(钉钉打卡考勤,要求较长工作时间常提及 996);不允许学生外出实习;学生补助处于学院较低水平;沟通风格被指生硬。',
        '2025-11-22',
      ),
      E(
        'daoshipingjia.net',
        'https://daoshipingjia.net/teacher/89413',
        '基于 2 条评价,综合评分 1.0/5。AI 总结指出指导能力方面被指责缺乏论文发表经验、难以有效指导学生、常将问题归咎于学生。',
        '2025-09-04',
      ),
      E(
        'blog.csdn.net',
        'https://blog.csdn.net/hzbooks/article/details/114529576',
        '易江芳,北京大学信息科学技术学院计算机系副教授,长期从事微处理器体系结构设计和性能优化科研及教学工作。',
        '2024-03-10',
      ),
    ],
    trace: [
      T('search', '搜索', '"易江芳 北大 评价" → 14 results'),
      T('read', '阅读', 'yanjubian.com/t/topic/7943 → 4500 chars'),
      T('read', '阅读', 'daoshipingjia.net/teacher/89413 → 2100 chars'),
      T('search', '搜索', '"易江芳 招生 2026" → 7 results'),
      T('read', '阅读', 'cs.pku.edu.cn/zsxx/yjszs/dsxx.htm → 3200 chars'),
      T('final', '提交评价', '招生·negative·conf=0.8'),
    ],
  },
  {
    id: 202,
    school: S('pku'),
    departments: [D('eecs', '计算机学院'), D('aiac', '人工智能研究院')],
    name_cn: '林徽因',
    title: '助理教授',
    homepage: 'https://cs.pku.edu.cn/info/1085/3201.htm',
    source_url: 'https://cs.pku.edu.cn/info/1085/3201.htm',
    email: 'linhy@pku.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: '研究方向:可信机器学习、隐私计算。北大博雅青年学者。',
    research_interests: ['可信机器学习', '隐私计算', '差分隐私', '联邦学习'],
    is_recruiting: true,
    recruiting_confidence: 0.9,
    reputation_tag: 'positive',
    enriched_summary:
      '林老师作为青年 PI,2026 年招博 2 名 + 硕 1 名。组里方向新且发表速度快。学生评价:导师 hands-on、每周 1-on-1、组里 PhD 平均 2 篇一作 / 年。适合想做可信 AI 方向的同学。',
    last_enriched_at: '2026-05-15T07:20:00Z',
    quotas: [
      Q(2026, 'PhD', 2, 0.9, '官网招生通知', 'https://cs.pku.edu.cn/lin-recruit'),
      Q(2026, 'MS', 1, 0.85, '硕士导师名单', 'https://cs.pku.edu.cn/zsxx/yjszs/dsxx.htm'),
    ],
    evaluations: [
      E(
        'zhihu.com',
        'https://zhihu.com/q/87651',
        '林老师是新 PI,有冲劲,组里氛围青春。',
        '2026-03-20',
      ),
    ],
    trace: [],
  },
  {
    id: 203,
    school: S('pku'),
    departments: [D('aiac', '人工智能研究院')],
    name_cn: '周翊安',
    title: '研究员',
    homepage: 'https://ai.pku.edu.cn/info/1019/1582.htm',
    source_url: 'https://ai.pku.edu.cn/info/1019/1582.htm',
    email: 'zhouya@pku.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['强化学习', '决策智能'],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: null,
    enriched_summary: null,
    last_enriched_at: null,
    quotas: [],
    evaluations: [],
    trace: [],
  },
  {
    id: 204,
    school: S('pku'),
    departments: [D('eecs', '计算机学院')],
    name_cn: '高翔宇',
    title: '教授',
    homepage: 'https://cs.pku.edu.cn/info/1085/1850.htm',
    source_url: 'https://cs.pku.edu.cn/info/1085/1850.htm',
    email: 'gaoxy@pku.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['编译器', '程序语言', '形式化方法'],
    is_recruiting: false,
    recruiting_confidence: 0.7,
    reputation_tag: 'positive',
    enriched_summary:
      '高老师 2026 年不招新博士(已满员),硕士仅接收推免生。学生评价正面,组氛围学术,适合理论方向。可关注 2027 年。',
    last_enriched_at: '2026-05-02T09:00:00Z',
    quotas: [
      Q(2026, 'PhD', 0, 0.85, '组主页:"2026 不招博士"', 'https://cs.pku.edu.cn/gao-recruit'),
    ],
    evaluations: [
      E(
        'yanjubian.com',
        'https://yanjubian.com/t/topic/6611',
        '高老师是大佬,做编译器方向少有的中文界知名学者,组里产出稳定。',
        '2026-01-08',
      ),
    ],
    trace: [],
  },
  {
    id: 205,
    school: S('pku'),
    departments: [D('eecs', '计算机学院')],
    name_cn: '何昭',
    title: '副教授',
    homepage: 'https://cs.pku.edu.cn/info/1085/2701.htm',
    source_url: 'https://cs.pku.edu.cn/info/1085/2701.htm',
    email: 'hezhao@pku.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: [],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: null,
    enriched_summary: null,
    last_enriched_at: null,
    quotas: [],
    evaluations: [],
    trace: [],
  },

  /* ============ 复旦大学 ============ */
  {
    id: 301,
    school: S('fudan'),
    departments: [D('cs', '计算机科学技术学院')],
    name_cn: '邱明远',
    title: '教授',
    homepage: 'https://cs.fudan.edu.cn/info/1083/12001.htm',
    source_url: 'https://cs.fudan.edu.cn/info/1083/12001.htm',
    email: 'qiumy@fudan.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: '复旦 MOSS 团队 PI,主要研究方向为自然语言处理与大语言模型。',
    research_interests: ['NLP', '大语言模型', 'Agent', '对话系统'],
    is_recruiting: true,
    recruiting_confidence: 0.9,
    reputation_tag: 'positive',
    enriched_summary:
      '邱老师组(MOSS 团队)2026 年招博 3 + 硕 4。组里资源充足、算力管够、有自研模型与工业合作。学生反馈整体正向:产出多、毕业去向好(头部大模型公司 offer 多),但工作节奏偏快。适合想做大模型的同学。',
    last_enriched_at: '2026-05-19T02:00:00Z',
    quotas: [
      Q(2026, 'PhD', 3, 0.9, '组招生页', 'https://nlp.fudan.edu.cn/recruit'),
      Q(2026, 'MS', 4, 0.85, '复旦官网硕士导师名单', 'https://cs.fudan.edu.cn/zsxx/yjszs.htm'),
    ],
    evaluations: [
      E(
        'zhihu.com',
        'https://zhihu.com/q/22011',
        '邱老师组是国内 NLP 第一梯队,有 MOSS 的工业经验,毕业去向很好。节奏快,适合 push 自己的同学。',
        '2026-04-20',
      ),
      E(
        'csrankings.org',
        'https://csrankings.org/qiumy',
        'h-index 42, 近 5 年 ACL/EMNLP/NAACL 41 篇。',
        '2026-01-01',
      ),
    ],
    trace: [],
  },
  {
    id: 302,
    school: S('fudan'),
    departments: [D('cs', '计算机科学技术学院'), D('bigdata', '大数据学院')],
    name_cn: '蒋怀远',
    title: '副教授',
    homepage: 'https://cs.fudan.edu.cn/info/1083/9920.htm',
    source_url: 'https://cs.fudan.edu.cn/info/1083/9920.htm',
    email: 'jianghy@fudan.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['数据挖掘', '图神经网络'],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: 'neutral',
    enriched_summary: null,
    last_enriched_at: '2026-04-18T03:00:00Z',
    quotas: [],
    evaluations: [],
    trace: [],
  },
  {
    id: 303,
    school: S('fudan'),
    departments: [D('cs', '计算机科学技术学院')],
    name_cn: '冯立铭',
    title: '青年研究员',
    homepage: 'https://cs.fudan.edu.cn/info/1083/15233.htm',
    source_url: 'https://cs.fudan.edu.cn/info/1083/15233.htm',
    email: 'lmfeng@fudan.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['计算机视觉', '医学影像'],
    is_recruiting: true,
    recruiting_confidence: 0.6,
    reputation_tag: null,
    enriched_summary: '冯老师 2025 年新入职,组里 1 博 1 硕,招生意愿强但样本少。',
    last_enriched_at: '2026-05-12T06:00:00Z',
    quotas: [Q(2026, 'MS', 1, 0.6, '邮件回复:"2026 年招 1 硕"', 'mailto:lmfeng@fudan.edu.cn')],
    evaluations: [],
    trace: [],
  },
  {
    id: 304,
    school: S('fudan'),
    departments: [D('aiken', '智能复杂体系实验室')],
    name_cn: '罗思宇',
    title: '教授',
    homepage: 'https://aiken.fudan.edu.cn/info/1010/3201.htm',
    source_url: 'https://aiken.fudan.edu.cn/info/1010/3201.htm',
    email: 'luosy@fudan.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['复杂系统', '社会计算'],
    is_recruiting: false,
    recruiting_confidence: 0.75,
    reputation_tag: 'negative',
    enriched_summary:
      '罗老师 2026 年不招博士。学生反馈负面:组里方向漂移、学生不易出成果、毕业延期常见。慎重考虑。',
    last_enriched_at: '2026-05-08T11:00:00Z',
    quotas: [
      Q(
        2026,
        'PhD',
        0,
        0.75,
        '组里同学反馈不再招博',
        'https://aiken.fudan.edu.cn/news/2025-11.html',
      ),
    ],
    evaluations: [
      E(
        'yanjubian.com',
        'https://yanjubian.com/t/topic/8842',
        '组里 5 年毕业是常态,论文产出依赖个人,组里支持有限。',
        '2025-12-12',
      ),
    ],
    trace: [],
  },
  {
    id: 305,
    school: S('fudan'),
    departments: [D('cs', '计算机科学技术学院')],
    name_cn: '沈雨晴',
    title: '副教授',
    homepage: 'https://cs.fudan.edu.cn/info/1083/10550.htm',
    source_url: 'https://cs.fudan.edu.cn/info/1083/10550.htm',
    email: 'shenyq@fudan.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: [],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: null,
    enriched_summary: null,
    last_enriched_at: null,
    quotas: [],
    evaluations: [],
    trace: [],
  },

  /* ============ 上海交通大学 ============ */
  {
    id: 401,
    school: S('sjtu'),
    departments: [D('cs', '计算机系'), D('jhc', 'John Hopcroft Center')],
    name_cn: '俞博文',
    title: '教授',
    homepage: 'https://cs.sjtu.edu.cn/info/1086/8801.htm',
    source_url: 'https://cs.sjtu.edu.cn/info/1086/8801.htm',
    email: 'yubw@sjtu.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: 'ACM 班长期任教,主要研究方向为机器学习理论。',
    research_interests: ['机器学习理论', '优化理论'],
    is_recruiting: true,
    recruiting_confidence: 0.85,
    reputation_tag: 'positive',
    enriched_summary:
      '俞老师组 2026 年招博 2 名,方向强理论,需要数学背景。组氛围学术、组会高密度、产出 JMLR/COLT 居多。适合想走 academia 的同学。',
    last_enriched_at: '2026-05-17T14:00:00Z',
    quotas: [Q(2026, 'PhD', 2, 0.9, '官网招生页', 'https://cs.sjtu.edu.cn/yu-recruit')],
    evaluations: [
      E(
        'zhihu.com',
        'https://zhihu.com/q/33442',
        '俞老师是国内做 ML 理论少有的大佬,组里 vibe 学术。',
        '2026-02-11',
      ),
    ],
    trace: [],
  },
  {
    id: 402,
    school: S('sjtu'),
    departments: [D('cs', '计算机系')],
    name_cn: '马天明',
    title: '副教授',
    homepage: 'https://cs.sjtu.edu.cn/info/1086/9931.htm',
    source_url: 'https://cs.sjtu.edu.cn/info/1086/9931.htm',
    email: 'matm@sjtu.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['操作系统', '存储系统'],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: 'neutral',
    enriched_summary: null,
    last_enriched_at: '2026-04-25T08:00:00Z',
    quotas: [],
    evaluations: [],
    trace: [],
  },
  {
    id: 403,
    school: S('sjtu'),
    departments: [D('ai', '人工智能学院')],
    name_cn: '黎清欢',
    title: '助理教授',
    homepage: 'https://ai.sjtu.edu.cn/info/1019/2201.htm',
    source_url: 'https://ai.sjtu.edu.cn/info/1019/2201.htm',
    email: 'liqh@sjtu.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: '研究方向:具身智能与机器人学习。',
    research_interests: ['具身智能', '机器人学习', '强化学习'],
    is_recruiting: true,
    recruiting_confidence: 0.8,
    reputation_tag: null,
    enriched_summary:
      '黎老师新入职 PI,2026 年招博 1 + 硕 2。组里有 6 台 Franka + 2 台 Unitree,硬件资源好。暂无学生评价。',
    last_enriched_at: '2026-05-14T03:30:00Z',
    quotas: [
      Q(2026, 'PhD', 1, 0.85, '官网公告', 'https://ai.sjtu.edu.cn/li-recruit'),
      Q(2026, 'MS', 2, 0.75, '硕士名单', 'https://ai.sjtu.edu.cn/zsxx.htm'),
    ],
    evaluations: [],
    trace: [],
  },
  {
    id: 404,
    school: S('sjtu'),
    departments: [D('cs', '计算机系')],
    name_cn: '邓凯文',
    title: '教授',
    homepage: 'https://cs.sjtu.edu.cn/info/1086/7001.htm',
    source_url: 'https://cs.sjtu.edu.cn/info/1086/7001.htm',
    email: 'dengkw@sjtu.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['密码学', '区块链'],
    is_recruiting: false,
    recruiting_confidence: 0.9,
    reputation_tag: 'unknown',
    enriched_summary: '邓老师 2026 年不招收新生(休假)。',
    last_enriched_at: '2026-04-12T03:00:00Z',
    quotas: [Q(2026, 'PhD', 0, 0.9, '组主页公告', 'https://cs.sjtu.edu.cn/deng-recruit')],
    evaluations: [],
    trace: [],
  },
  {
    id: 405,
    school: S('sjtu'),
    departments: [D('cs', '计算机系')],
    name_cn: '夏晨',
    title: '副教授',
    homepage: 'https://cs.sjtu.edu.cn/info/1086/8120.htm',
    source_url: 'https://cs.sjtu.edu.cn/info/1086/8120.htm',
    email: 'xiachen@sjtu.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: [],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: null,
    enriched_summary: null,
    last_enriched_at: null,
    quotas: [],
    evaluations: [],
    trace: [],
  },

  /* ============ 南京大学 ============ */
  {
    id: 501,
    school: S('nju'),
    departments: [D('cs', '计算机科学与技术系'), D('ai', '人工智能学院')],
    name_cn: '周文君',
    title: '教授',
    homepage: 'https://cs.nju.edu.cn/wenjun/index.htm',
    source_url: 'https://cs.nju.edu.cn/wenjun/index.htm',
    email: 'zhouwj@nju.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: 'LAMDA 组 PI,主要研究方向为机器学习与数据挖掘。',
    research_interests: ['集成学习', '弱监督学习', '机器学习'],
    is_recruiting: true,
    recruiting_confidence: 0.9,
    reputation_tag: 'positive',
    enriched_summary:
      '周老师组(LAMDA)是国内 ML 顶级 lab。2026 年招博 2 + 硕 3。组氛围学术、产出稳定、毕业去向好(国内外名校教职 + 头部公司)。建议尽早联系。',
    last_enriched_at: '2026-05-16T10:00:00Z',
    quotas: [
      Q(2026, 'PhD', 2, 0.9, 'LAMDA 招生页', 'https://lamda.nju.edu.cn/recruit'),
      Q(2026, 'MS', 3, 0.85, '硕士导师名单', 'https://cs.nju.edu.cn/zsxx.htm'),
    ],
    evaluations: [
      E(
        'zhihu.com',
        'https://zhihu.com/q/44551',
        'LAMDA 在国内 ML 界口碑顶尖,周老师组是其中标杆。',
        '2026-03-08',
      ),
    ],
    trace: [],
  },
  {
    id: 502,
    school: S('nju'),
    departments: [D('cs', '计算机科学与技术系')],
    name_cn: '吕承晋',
    title: '副教授',
    homepage: 'https://cs.nju.edu.cn/lvcj/index.htm',
    source_url: 'https://cs.nju.edu.cn/lvcj/index.htm',
    email: 'lvcj@nju.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['软件工程', '程序分析'],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: 'neutral',
    enriched_summary: null,
    last_enriched_at: '2026-04-20T03:00:00Z',
    quotas: [],
    evaluations: [],
    trace: [],
  },
  {
    id: 503,
    school: S('nju'),
    departments: [D('ai', '人工智能学院')],
    name_cn: '丁亦琛',
    title: '助理教授',
    homepage: 'https://ai.nju.edu.cn/dyc/index.htm',
    source_url: 'https://ai.nju.edu.cn/dyc/index.htm',
    email: 'dingyc@nju.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['强化学习', '多智能体'],
    is_recruiting: true,
    recruiting_confidence: 0.7,
    reputation_tag: null,
    enriched_summary: null,
    last_enriched_at: '2026-04-30T05:00:00Z',
    quotas: [Q(2026, 'MS', null, 0.7, '邮件回复"可招"', 'mailto:dingyc@nju.edu.cn')],
    evaluations: [],
    trace: [],
  },
  {
    id: 504,
    school: S('nju'),
    departments: [D('cs', '计算机科学与技术系')],
    name_cn: '宋柏霖',
    title: '教授',
    homepage: 'https://cs.nju.edu.cn/songbl/index.htm',
    source_url: 'https://cs.nju.edu.cn/songbl/index.htm',
    email: 'songbl@nju.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: [],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: null,
    enriched_summary: null,
    last_enriched_at: null,
    quotas: [],
    evaluations: [],
    trace: [],
  },
  {
    id: 505,
    school: S('nju'),
    departments: [D('ai', '人工智能学院')],
    name_cn: '范允中',
    title: '副教授',
    homepage: 'https://ai.nju.edu.cn/fyz/index.htm',
    source_url: 'https://ai.nju.edu.cn/fyz/index.htm',
    email: 'fanyz@nju.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['图神经网络', '推荐系统'],
    is_recruiting: false,
    recruiting_confidence: 0.7,
    reputation_tag: 'negative',
    enriched_summary: '范老师 2026 年不招新生。少量评价反馈管理风格压力大、组内沟通紧张,慎重考虑。',
    last_enriched_at: '2026-05-04T08:00:00Z',
    quotas: [],
    evaluations: [
      E(
        'daoshipingjia.net',
        'https://daoshipingjia.net/teacher/51209',
        '综合 2.1/5。学生反馈组里管理严格、缺乏支持。',
        '2025-11-30',
      ),
    ],
    trace: [],
  },

  /* ============ 浙江大学 ============ */
  {
    id: 601,
    school: S('zju'),
    departments: [D('cs', '计算机科学与技术学院'), D('cad', 'CAD&CG 国家重点实验室')],
    name_cn: '潘思齐',
    title: '教授',
    homepage: 'https://person.zju.edu.cn/pansq',
    source_url: 'https://person.zju.edu.cn/pansq',
    email: 'pansq@zju.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['计算机图形学', '渲染', '几何处理'],
    is_recruiting: true,
    recruiting_confidence: 0.85,
    reputation_tag: 'positive',
    enriched_summary:
      '潘老师(CAD 国重)2026 年招博 2 + 硕 2,方向偏图形学传统强项。组里 SIGGRAPH 产出稳定,毕业去向好(国内外大厂图形/游戏组)。',
    last_enriched_at: '2026-05-18T08:30:00Z',
    quotas: [Q(2026, 'PhD', 2, 0.9, '官网招生页', 'https://cad.zju.edu.cn/recruit')],
    evaluations: [
      E(
        'zhihu.com',
        'https://zhihu.com/q/55663',
        '组里图形学传统优势,导师 hands-on,毕业去向好。',
        '2026-02-22',
      ),
    ],
    trace: [],
  },
  {
    id: 602,
    school: S('zju'),
    departments: [D('cs', '计算机科学与技术学院')],
    name_cn: '楚星河',
    title: '副教授',
    homepage: 'https://person.zju.edu.cn/chuxh',
    source_url: 'https://person.zju.edu.cn/chuxh',
    email: 'chuxh@zju.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['推荐系统', '信息检索'],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: 'neutral',
    enriched_summary: null,
    last_enriched_at: '2026-04-15T03:00:00Z',
    quotas: [],
    evaluations: [],
    trace: [],
  },
  {
    id: 603,
    school: S('zju'),
    departments: [D('ai', 'AI 研究所')],
    name_cn: '司徒岚',
    title: '研究员',
    homepage: 'https://person.zju.edu.cn/sitl',
    source_url: 'https://person.zju.edu.cn/sitl',
    email: 'sitl@zju.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['多模态学习'],
    is_recruiting: true,
    recruiting_confidence: 0.75,
    reputation_tag: null,
    enriched_summary: null,
    last_enriched_at: '2026-05-09T05:00:00Z',
    quotas: [Q(2026, 'MS', 2, 0.75, '硕士导师名单', 'https://cs.zju.edu.cn/zsxx.htm')],
    evaluations: [],
    trace: [],
  },
  {
    id: 604,
    school: S('zju'),
    departments: [D('cs', '计算机科学与技术学院')],
    name_cn: '游冠宇',
    title: '助理教授',
    homepage: 'https://person.zju.edu.cn/yougy',
    source_url: 'https://person.zju.edu.cn/yougy',
    email: 'yougy@zju.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: [],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: null,
    enriched_summary: null,
    last_enriched_at: null,
    quotas: [],
    evaluations: [],
    trace: [],
  },
  {
    id: 605,
    school: S('zju'),
    departments: [D('cs', '计算机科学与技术学院')],
    name_cn: '简云朗',
    title: '教授',
    homepage: 'https://person.zju.edu.cn/jianyl',
    source_url: 'https://person.zju.edu.cn/jianyl',
    email: 'jianyl@zju.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['数据库', '云计算'],
    is_recruiting: false,
    recruiting_confidence: 0.6,
    reputation_tag: 'unknown',
    enriched_summary: '简老师 2026 年暂不招新生(创业中)。',
    last_enriched_at: '2026-04-20T05:00:00Z',
    quotas: [],
    evaluations: [],
    trace: [],
  },

  /* ============ 中国科学技术大学 ============ */
  {
    id: 701,
    school: S('ustc'),
    departments: [D('cs', '计算机学院'), D('ai', '人工智能学院')],
    name_cn: '霍承烨',
    title: '教授',
    homepage: 'http://staff.ustc.edu.cn/~huocy',
    source_url: 'http://staff.ustc.edu.cn/~huocy',
    email: 'huocy@ustc.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['量子计算', '量子机器学习'],
    is_recruiting: true,
    recruiting_confidence: 0.8,
    reputation_tag: 'positive',
    enriched_summary:
      '霍老师组方向偏量子+ML 的交叉,2026 招博 2。组里小而精,人均产出高,需要物理基础。学生评价正向,组氛围 collaborative。',
    last_enriched_at: '2026-05-13T07:00:00Z',
    quotas: [Q(2026, 'PhD', 2, 0.85, '官网招生页', 'http://staff.ustc.edu.cn/~huocy/recruit')],
    evaluations: [
      E(
        'zhihu.com',
        'https://zhihu.com/q/66721',
        '霍老师组方向 niche 但前沿,适合想做交叉方向的同学。',
        '2026-01-30',
      ),
    ],
    trace: [],
  },
  {
    id: 702,
    school: S('ustc'),
    departments: [D('cs', '计算机学院')],
    name_cn: '苏哲昊',
    title: '特任副教授',
    homepage: 'http://staff.ustc.edu.cn/~suzh',
    source_url: 'http://staff.ustc.edu.cn/~suzh',
    email: 'suzh@ustc.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['NLP', '信息抽取'],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: null,
    enriched_summary: null,
    last_enriched_at: null,
    quotas: [],
    evaluations: [],
    trace: [],
  },
  {
    id: 703,
    school: S('ustc'),
    departments: [D('ai', '人工智能学院')],
    name_cn: '尉沛然',
    title: '副教授',
    homepage: 'http://staff.ustc.edu.cn/~weipr',
    source_url: 'http://staff.ustc.edu.cn/~weipr',
    email: 'weipr@ustc.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['CV', '视频理解'],
    is_recruiting: true,
    recruiting_confidence: 0.75,
    reputation_tag: 'neutral',
    enriched_summary: null,
    last_enriched_at: '2026-04-28T03:00:00Z',
    quotas: [Q(2026, 'MS', 2, 0.75, '硕士名单', 'http://cs.ustc.edu.cn/zsxx.htm')],
    evaluations: [],
    trace: [],
  },
  {
    id: 704,
    school: S('ustc'),
    departments: [D('cs', '计算机学院')],
    name_cn: '颜玮岚',
    title: '教授',
    homepage: 'http://staff.ustc.edu.cn/~yanwl',
    source_url: 'http://staff.ustc.edu.cn/~yanwl',
    email: null,
    email_obfuscated: true,
    phone: null,
    photo_url: null,
    bio_text: '主页邮箱采用图片显示,需手动获取',
    research_interests: [],
    is_recruiting: null,
    recruiting_confidence: null,
    reputation_tag: null,
    enriched_summary: null,
    last_enriched_at: null,
    quotas: [],
    evaluations: [],
    trace: [],
  },
  {
    id: 705,
    school: S('ustc'),
    departments: [D('cs', '计算机学院')],
    name_cn: '甘明哲',
    title: '助理教授',
    homepage: 'http://staff.ustc.edu.cn/~ganmz',
    source_url: 'http://staff.ustc.edu.cn/~ganmz',
    email: 'ganmz@ustc.edu.cn',
    email_obfuscated: false,
    phone: null,
    photo_url: null,
    bio_text: null,
    research_interests: ['分布式系统'],
    is_recruiting: false,
    recruiting_confidence: 0.7,
    reputation_tag: 'negative',
    enriched_summary:
      '甘老师 2026 年不招收新生。已有学生反馈组里管理偏激进、缺乏指导,毕业延期较多。',
    last_enriched_at: '2026-05-01T03:00:00Z',
    quotas: [],
    evaluations: [
      E(
        'yanjubian.com',
        'https://yanjubian.com/t/topic/9112',
        '组里 push 强,导师对学生预期高,但实际指导有限。',
        '2025-12-20',
      ),
    ],
    trace: [],
  },
]

export function schoolDepts(schoolCode: SchoolCode): Department[] {
  const seen = new Map<string, Department>()
  ADVISORS.filter((a) => a.school.code === schoolCode).forEach((a) => {
    a.departments.forEach((d) => {
      if (!seen.has(d.code)) seen.set(d.code, d)
    })
  })
  return Array.from(seen.values())
}

export function formatRelTime(iso: string | null | undefined): string | null {
  if (!iso) return null
  const now = Date.now()
  const t = new Date(iso).getTime()
  const diff = Math.max(0, now - t)
  const d = Math.floor(diff / 86400000)
  if (d < 1) return '今天'
  if (d < 30) return `${d} 天前`
  if (d < 365) return `${Math.floor(d / 30)} 月前`
  return `${Math.floor(d / 365)} 年前`
}
